export const pizzaData = {
  topPicks: [
    {
      name: "The Sampler",
      img: "./Images/Food/sampler.png",
      ingredients: [
        "Our Signature Sauce",
        "Smoked Provolone Cheese",
        "Pepperoni",
        "Canadian Bacon",
        "Hamburger",
        "Mild Sausage",
        "Onions",
        "Bell Peppers",
        "Green Olives",
        "Black Olives",
        "Jalapenos",
      ],
    },
    {
      name: "The Meat Market",
      img: "./Images/Food/meat-market.png",
      ingredients: [
        "Our Signature Sauce",
        "Smoked Provolone Cheese",
        "Pepperoni",
        "Canadian Bacon",
        "Hamburger",
        "Mild Sausage",
        "Italian Sausage",
      ],
    },
    {
      name: "The Veggie",
      img: "./Images/Food/veggie.png",
      ingredients: [
        "Our Signature Sauce",
        "Smoked Provolone Cheese",
        "Onions",
        "Bell Pepper",
        "Green Olives",
        "Black Olives",
        "Tomatoes",
        "Jalapenos",
      ],
    },
  ],

  otherSpecialties: [
    {
      name: "The BBQ",
      img: "./Images/Food/bbq-chicken.png",
      ingredients: [
        "Smokehouse BBQ Sauce",
        "Smoked Provolone Cheese",
        "Grilled Chicken",
        "Purple Onions",
        "Cheddar Cheese",
      ],
    },
    {
      name: "The Buffalo",
      img: "./Images/Food/buffalo-chicken.png",
      ingredients: [
        "Garlic Butter",
        "Franks Red Hot Sauce",
        "Smoked Provolone Cheese",
        "Grilled Chicken",
        "Cheddar Cheese",
      ],
    },
    {
      name: "The Deluxe",
      img: "./Images/Food/deluxe.png",
      ingredients: [
        "Our Signature Sauce",
        "Smoked Provolone Cheese",
        "Pepperoni",
        "Mild Sausage",
        "Onions",
        "Bell Peppers",
        "Black Olives",
      ],
    },
    {
      name: "The Bacon Cheeseburger",
      img: "./Images/Food/bacon-cheeseburger.png",
      ingredients: [
        "Our Signature Sauce",
        "Smoked Provolone Cheese",
        "Hamburger",
        "Tomatoes",
        "Onions",
        "Cheddar Cheese",
      ],
    },
    {
      name: "The Spinach",
      img: "./Images/Food/spinach-pizza.png",
      ingredients: [
        "Garlic Butter",
        "Spinach Alfredo Sauce",
        "Smoked Provolone Cheese",
        "Tomatoes",
        "Purple Onions",
        "Cheddar Cheese",
      ],
    },
  ],
  allToppings: {
    sauces: [
      "Our Signature Sauce",
      "Garlic Butter",
      "BBQ Sauce",
      "Ranch",
      "Spinach Alfredo Sauce",
    ],
    cheeses: ["Smoked Provolone Cheese", "Cheddar Cheese"],
    meats: [
      "Pepperoni",
      "Canadian Bacon",
      "Hamburger",
      "Mild Sausage",
      "Italian Sausage",
      "Chorizo",
      "Bacon",
      "Anchovies",
    ],
    veggies: [
      "White Onions",
      "Purple Onions",
      "Bell Peppers",
      "Green Olives",
      "Black Olives",
      "Jalapenos",
      "Tomatoes",
    ],
  },
};
